<a href="https://colab.research.google.com/github/jaydevpaul/ML_from_Scratch/blob/main/MultipleLinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
data=pd.read_csv('/content/50_Startups.csv')

In [4]:
x=data.iloc[:,:-1]
y=data.iloc[:,-1]
print(x)


    R&D Spend  Administration  Marketing Spend       State
0   165349.20       136897.80        471784.10    New York
1   162597.70       151377.59        443898.53  California
2   153441.51       101145.55        407934.54     Florida
3   144372.41       118671.85        383199.62    New York
4   142107.34        91391.77        366168.42     Florida
5   131876.90        99814.71        362861.36    New York
6   134615.46       147198.87        127716.82  California
7   130298.13       145530.06        323876.68     Florida
8   120542.52       148718.95        311613.29    New York
9   123334.88       108679.17        304981.62  California
10  101913.08       110594.11        229160.95     Florida
11  100671.96        91790.61        249744.55  California
12   93863.75       127320.38        249839.44     Florida
13   91992.39       135495.07        252664.93  California
14  119943.24       156547.42        256512.92     Florida
15  114523.61       122616.84        261776.23    New Yo

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(
    transformers=[('encoder',OneHotEncoder(),[3])],
    remainder='passthrough'
    )

In [8]:
x = np.array(ct.fit_transform(x))

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
print(x_train)

[[     0.        1.        0.    55493.95 103057.49 214634.81]
 [     0.        0.        1.    46014.02  85047.44 205517.64]
 [     0.        1.        0.    75328.87 144135.98 134050.07]
 [     1.        0.        0.    46426.07 157693.92 210797.67]
 [     0.        1.        0.    91749.16 114175.79 294919.57]
 [     0.        1.        0.   130298.13 145530.06 323876.68]
 [     0.        1.        0.   119943.24 156547.42 256512.92]
 [     0.        0.        1.     1000.23 124153.04   1903.93]
 [     0.        0.        1.      542.05  51743.15      0.  ]
 [     0.        0.        1.    65605.48 153032.06 107138.38]
 [     0.        0.        1.   114523.61 122616.84 261776.23]
 [     0.        1.        0.    61994.48 115641.28  91131.24]
 [     1.        0.        0.    63408.86 129219.61  46085.25]
 [     1.        0.        0.    78013.11 121597.55 264346.06]
 [     1.        0.        0.    23640.93  96189.63 148001.11]
 [     1.        0.        0.    76253.86 113867.3  298

In [16]:
np.set_printoptions(suppress=True)


In [17]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [20]:
y_test=np.array(y_test)
pred=regressor.predict(x_test)
np.set_printoptions(precision=2)
np.concatenate((pred.reshape(len(pred),1),y_test.reshape(len(y_test),1)),1)

array([[103015.2 , 103282.38],
       [132582.28, 144259.4 ],
       [132447.74, 146121.95],
       [ 71976.1 ,  77798.83],
       [178537.48, 191050.39],
       [116161.24, 105008.31],
       [ 67851.69,  81229.06],
       [ 98791.73,  97483.56],
       [113969.44, 110352.25],
       [167921.07, 166187.94]])

In [21]:
regressor.coef_

array([  86.64, -872.65,  786.01,    0.77,    0.03,    0.04])

In [22]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [23]:
x_test

array([[     0.  ,      1.  ,      0.  ,  66051.52, 182645.56, 118148.2 ],
       [     1.  ,      0.  ,      0.  , 100671.96,  91790.61, 249744.55],
       [     0.  ,      1.  ,      0.  , 101913.08, 110594.11, 229160.95],
       [     0.  ,      1.  ,      0.  ,  27892.92,  84710.77, 164470.71],
       [     0.  ,      1.  ,      0.  , 153441.51, 101145.55, 407934.54],
       [     0.  ,      0.  ,      1.  ,  72107.6 , 127864.55, 353183.81],
       [     0.  ,      0.  ,      1.  ,  20229.59,  65947.93, 185265.1 ],
       [     0.  ,      0.  ,      1.  ,  61136.38, 152701.92,  88218.23],
       [     0.  ,      1.  ,      0.  ,  73994.56, 122782.75, 303319.26],
       [     0.  ,      1.  ,      0.  , 142107.34,  91391.77, 366168.42]])